# Generated by Django 5.0 on 2023-12-14 15:49

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_playlist_last_updated_alter_recording_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='epg_cache_directory',
            field=models.TextField(default=record.models.random_file_name),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_cache_file',
            field=models.TextField(default=record.models.random_file_name),
        ),
        migrations.AddField(
            model_name='playlist',
            name='refresh_gap',
            field=models.IntegerField(default=12),
        ),
    ]
