# Generated by Django 5.0 on 2023-12-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0009_remove_playlist_writing_directory_userdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recording",
            options={"ordering": ("-start_time",)},
        ),
        migrations.AlterModelOptions(
            name="videosource",
            options={"ordering": ("index",)},
        ),
        migrations.AddField(
            model_name="videosource",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
