# Generated by Django 5.0 on 2025-02-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0012_recordingmethod_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videosource",
            old_name="recording_method_new",
            new_name="recording_method",
        ),
        migrations.RemoveField(
            model_name="videosource",
            name="recording_method_old",
        ),
    ]
