# Generated by Django 5.0 on 2025-02-23 07:19

import django.db.models.deletion
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    RecordingMethod = apps.get_model('record', 'RecordingMethod')
    RecordingMethod.objects.filter(name="ffmpeg").update(command='ffmpeg -user_agent "VLC/3.0.9 LibVLC/3.0.9" -i "{video_url}" -c copy "{output_file_path}"', termination_string='q')
    RecordingMethod.objects.filter(name="wget").update(command='wget --user-agent="VLC/3.0.9 LibVLC/3.0.9" "{video_url}" -O "{output_file_path}"')

class Migration(migrations.Migration):

    dependencies = [
        (
            "record",
            "0013_rename_recording_method_new_videosource_recording_method_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingmethod",
            name="termination_string",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="videosource",
            name="recording_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_sources",
                to="record.recordingmethod",
            ),
        ),
        migrations.RunPython(migrate_data)
    ]
