# Generated by Django 5.0 on 2025-02-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0014_recordingmethod_termination_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="epg_url",
        ),
    ]
