# Generated by Django 5.1.6 on 2025-02-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0015_remove_playlist_epg_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="epg_cache_directory",
        ),
    ]
